# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x07\x61gentgw\"\x9e\x01\n\rAgentRegister\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nagent_type\x18\x02 \x01(\t\x12\x36\n\x08metadata\x18\x03 \x03(\x0b\x32$.agentgw.AgentRegister.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9a\x01\n\x0c\x41gentMessage\x12*\n\x08register\x18\x01 \x01(\x0b\x32\x16.agentgw.AgentRegisterH\x00\x12*\n\x08response\x18\x02 \x01(\x0b\x32\x16.agentgw.AgentResponseH\x00\x12\'\n\theartbeat\x18\x03 \x01(\x0b\x32\x12.agentgw.HeartbeatH\x00\x42\t\n\x07payload\"n\n\x0eGatewayMessage\x12(\n\x07request\x18\x01 \x01(\x0b\x32\x15.agentgw.AgentRequestH\x00\x12\'\n\theartbeat\x18\x02 \x01(\x0b\x32\x12.agentgw.HeartbeatH\x00\x42\t\n\x07payload\"\xdb\x01\n\x0c\x41gentRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12&\n\x08messages\x18\x04 \x03(\x0b\x32\x14.agentgw.ChatMessage\x12\x39\n\nparameters\x18\x05 \x03(\x0b\x32%.agentgw.AgentRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa0\x01\n\rAgentResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\'\n\x07message\x18\x03 \x01(\x0b\x32\x14.agentgw.ChatMessageH\x00\x12%\n\x05\x63hunk\x18\x04 \x01(\x0b\x32\x14.agentgw.StreamChunkH\x00\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x42\t\n\x07\x63ontent\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"9\n\x0bStreamChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x19\n\x11reasoning_content\x18\x02 \x01(\t\"\x1e\n\tHeartbeat\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x32M\n\x0c\x41gentGateway\x12=\n\x07\x43onnect\x12\x15.agentgw.AgentMessage\x1a\x17.agentgw.GatewayMessage(\x01\x30\x01\x42&Z$github.com/wereliang/aiagw/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/wereliang/aiagw/api/proto'
  _globals['_AGENTREGISTER_METADATAENTRY']._loaded_options = None
  _globals['_AGENTREGISTER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AGENTREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_AGENTREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_AGENTREGISTER']._serialized_start=25
  _globals['_AGENTREGISTER']._serialized_end=183
  _globals['_AGENTREGISTER_METADATAENTRY']._serialized_start=136
  _globals['_AGENTREGISTER_METADATAENTRY']._serialized_end=183
  _globals['_AGENTMESSAGE']._serialized_start=186
  _globals['_AGENTMESSAGE']._serialized_end=340
  _globals['_GATEWAYMESSAGE']._serialized_start=342
  _globals['_GATEWAYMESSAGE']._serialized_end=452
  _globals['_AGENTREQUEST']._serialized_start=455
  _globals['_AGENTREQUEST']._serialized_end=674
  _globals['_AGENTREQUEST_PARAMETERSENTRY']._serialized_start=625
  _globals['_AGENTREQUEST_PARAMETERSENTRY']._serialized_end=674
  _globals['_AGENTRESPONSE']._serialized_start=677
  _globals['_AGENTRESPONSE']._serialized_end=837
  _globals['_CHATMESSAGE']._serialized_start=839
  _globals['_CHATMESSAGE']._serialized_end=883
  _globals['_STREAMCHUNK']._serialized_start=885
  _globals['_STREAMCHUNK']._serialized_end=942
  _globals['_HEARTBEAT']._serialized_start=944
  _globals['_HEARTBEAT']._serialized_end=974
  _globals['_AGENTGATEWAY']._serialized_start=976
  _globals['_AGENTGATEWAY']._serialized_end=1053
# @@protoc_insertion_point(module_scope)
