// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegister) Reset() {
	*x = AgentRegister{}
	mi := &file_api_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegister) ProtoMessage() {}

func (x *AgentRegister) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegister.ProtoReflect.Descriptor instead.
func (*AgentRegister) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegister) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegister) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentRegister) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Response
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *AgentRegister {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetResponse() *AgentResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *AgentRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Response struct {
	Response *AgentResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Response) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_Request
	//	*GatewayMessage_Heartbeat
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetRequest() *AgentRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *GatewayMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_Request struct {
	Request *AgentRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type GatewayMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*GatewayMessage_Request) isGatewayMessage_Payload() {}

func (*GatewayMessage_Heartbeat) isGatewayMessage_Payload() {}

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AgentRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type AgentResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*AgentResponse_Message
	//	*AgentResponse_Chunk
	Content       isAgentResponse_Content `protobuf_oneof:"content"`
	Done          bool                    `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentResponse) GetContent() isAgentResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentResponse) GetMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Content.(*AgentResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *AgentResponse) GetChunk() *StreamChunk {
	if x != nil {
		if x, ok := x.Content.(*AgentResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *AgentResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type isAgentResponse_Content interface {
	isAgentResponse_Content()
}

type AgentResponse_Message struct {
	Message *ChatMessage `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type AgentResponse_Chunk struct {
	Chunk *StreamChunk `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"`
}

func (*AgentResponse_Message) isAgentResponse_Content() {}

func (*AgentResponse_Chunk) isAgentResponse_Content() {}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StreamChunk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ReasoningContent string                 `protobuf:"bytes,2,opt,name=reasoning_content,json=reasoningContent,proto3" json:"reasoning_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_api_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamChunk) GetReasoningContent() string {
	if x != nil {
		return x.ReasoningContent
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/agent.proto\x12\aagentgw\"\xc8\x01\n" +
	"\rAgentRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.agentgw.AgentRegister.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\fAgentMessage\x124\n" +
	"\bregister\x18\x01 \x01(\v2\x16.agentgw.AgentRegisterH\x00R\bregister\x124\n" +
	"\bresponse\x18\x02 \x01(\v2\x16.agentgw.AgentResponseH\x00R\bresponse\x122\n" +
	"\theartbeat\x18\x03 \x01(\v2\x12.agentgw.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x82\x01\n" +
	"\x0eGatewayMessage\x121\n" +
	"\arequest\x18\x01 \x01(\v2\x15.agentgw.AgentRequestH\x00R\arequest\x122\n" +
	"\theartbeat\x18\x02 \x01(\v2\x12.agentgw.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x9a\x02\n" +
	"\fAgentRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x120\n" +
	"\bmessages\x18\x04 \x03(\v2\x14.agentgw.ChatMessageR\bmessages\x12E\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2%.agentgw.AgentRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\rAgentResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x120\n" +
	"\amessage\x18\x03 \x01(\v2\x14.agentgw.ChatMessageH\x00R\amessage\x12,\n" +
	"\x05chunk\x18\x04 \x01(\v2\x14.agentgw.StreamChunkH\x00R\x05chunk\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04doneB\t\n" +
	"\acontent\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"T\n" +
	"\vStreamChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12+\n" +
	"\x11reasoning_content\x18\x02 \x01(\tR\x10reasoningContent\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2M\n" +
	"\fAgentGateway\x12=\n" +
	"\aConnect\x12\x15.agentgw.AgentMessage\x1a\x17.agentgw.GatewayMessage(\x010\x01B&Z$github.com/wereliang/aiagw/api/protob\x06proto3"

var (
	file_api_proto_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_proto_rawDescData []byte
)

func file_api_proto_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_proto_rawDescData
}

var file_api_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_agent_proto_goTypes = []any{
	(*AgentRegister)(nil),  // 0: agentgw.AgentRegister
	(*AgentMessage)(nil),   // 1: agentgw.AgentMessage
	(*GatewayMessage)(nil), // 2: agentgw.GatewayMessage
	(*AgentRequest)(nil),   // 3: agentgw.AgentRequest
	(*AgentResponse)(nil),  // 4: agentgw.AgentResponse
	(*ChatMessage)(nil),    // 5: agentgw.ChatMessage
	(*StreamChunk)(nil),    // 6: agentgw.StreamChunk
	(*Heartbeat)(nil),      // 7: agentgw.Heartbeat
	nil,                    // 8: agentgw.AgentRegister.MetadataEntry
	nil,                    // 9: agentgw.AgentRequest.ParametersEntry
}
var file_api_proto_agent_proto_depIdxs = []int32{
	8,  // 0: agentgw.AgentRegister.metadata:type_name -> agentgw.AgentRegister.MetadataEntry
	0,  // 1: agentgw.AgentMessage.register:type_name -> agentgw.AgentRegister
	4,  // 2: agentgw.AgentMessage.response:type_name -> agentgw.AgentResponse
	7,  // 3: agentgw.AgentMessage.heartbeat:type_name -> agentgw.Heartbeat
	3,  // 4: agentgw.GatewayMessage.request:type_name -> agentgw.AgentRequest
	7,  // 5: agentgw.GatewayMessage.heartbeat:type_name -> agentgw.Heartbeat
	5,  // 6: agentgw.AgentRequest.messages:type_name -> agentgw.ChatMessage
	9,  // 7: agentgw.AgentRequest.parameters:type_name -> agentgw.AgentRequest.ParametersEntry
	5,  // 8: agentgw.AgentResponse.message:type_name -> agentgw.ChatMessage
	6,  // 9: agentgw.AgentResponse.chunk:type_name -> agentgw.StreamChunk
	1,  // 10: agentgw.AgentGateway.Connect:input_type -> agentgw.AgentMessage
	2,  // 11: agentgw.AgentGateway.Connect:output_type -> agentgw.GatewayMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_agent_proto_init() }
func file_api_proto_agent_proto_init() {
	if File_api_proto_agent_proto != nil {
		return
	}
	file_api_proto_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Response)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_api_proto_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*GatewayMessage_Request)(nil),
		(*GatewayMessage_Heartbeat)(nil),
	}
	file_api_proto_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentResponse_Message)(nil),
		(*AgentResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_proto = out.File
	file_api_proto_agent_proto_goTypes = nil
	file_api_proto_agent_proto_depIdxs = nil
}
