// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/internal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayInternal_ForwardRequest_FullMethodName = "/agentgw.GatewayInternal/ForwardRequest"
)

// GatewayInternalClient is the client API for GatewayInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayInternalClient interface {
	ForwardRequest(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentResponse], error)
}

type gatewayInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayInternalClient(cc grpc.ClientConnInterface) GatewayInternalClient {
	return &gatewayInternalClient{cc}
}

func (c *gatewayInternalClient) ForwardRequest(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayInternal_ServiceDesc.Streams[0], GatewayInternal_ForwardRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentRequest, AgentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayInternal_ForwardRequestClient = grpc.ServerStreamingClient[AgentResponse]

// GatewayInternalServer is the server API for GatewayInternal service.
// All implementations must embed UnimplementedGatewayInternalServer
// for forward compatibility.
type GatewayInternalServer interface {
	ForwardRequest(*AgentRequest, grpc.ServerStreamingServer[AgentResponse]) error
	mustEmbedUnimplementedGatewayInternalServer()
}

// UnimplementedGatewayInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayInternalServer struct{}

func (UnimplementedGatewayInternalServer) ForwardRequest(*AgentRequest, grpc.ServerStreamingServer[AgentResponse]) error {
	return status.Error(codes.Unimplemented, "method ForwardRequest not implemented")
}
func (UnimplementedGatewayInternalServer) mustEmbedUnimplementedGatewayInternalServer() {}
func (UnimplementedGatewayInternalServer) testEmbeddedByValue()                         {}

// UnsafeGatewayInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayInternalServer will
// result in compilation errors.
type UnsafeGatewayInternalServer interface {
	mustEmbedUnimplementedGatewayInternalServer()
}

func RegisterGatewayInternalServer(s grpc.ServiceRegistrar, srv GatewayInternalServer) {
	// If the following call panics, it indicates UnimplementedGatewayInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayInternal_ServiceDesc, srv)
}

func _GatewayInternal_ForwardRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayInternalServer).ForwardRequest(m, &grpc.GenericServerStream[AgentRequest, AgentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayInternal_ForwardRequestServer = grpc.ServerStreamingServer[AgentResponse]

// GatewayInternal_ServiceDesc is the grpc.ServiceDesc for GatewayInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentgw.GatewayInternal",
	HandlerType: (*GatewayInternalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ForwardRequest",
			Handler:       _GatewayInternal_ForwardRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/internal.proto",
}
