// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/internal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_internal_proto protoreflect.FileDescriptor

const file_api_proto_internal_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/internal.proto\x12\aagentgw\x1a\x15api/proto/agent.proto2T\n" +
	"\x0fGatewayInternal\x12A\n" +
	"\x0eForwardRequest\x12\x15.agentgw.AgentRequest\x1a\x16.agentgw.AgentResponse0\x01B&Z$github.com/wereliang/aiagw/api/protob\x06proto3"

var file_api_proto_internal_proto_goTypes = []any{
	(*AgentRequest)(nil),  // 0: agentgw.AgentRequest
	(*AgentResponse)(nil), // 1: agentgw.AgentResponse
}
var file_api_proto_internal_proto_depIdxs = []int32{
	0, // 0: agentgw.GatewayInternal.ForwardRequest:input_type -> agentgw.AgentRequest
	1, // 1: agentgw.GatewayInternal.ForwardRequest:output_type -> agentgw.AgentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_internal_proto_init() }
func file_api_proto_internal_proto_init() {
	if File_api_proto_internal_proto != nil {
		return
	}
	file_api_proto_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_internal_proto_rawDesc), len(file_api_proto_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_internal_proto_goTypes,
		DependencyIndexes: file_api_proto_internal_proto_depIdxs,
	}.Build()
	File_api_proto_internal_proto = out.File
	file_api_proto_internal_proto_goTypes = nil
	file_api_proto_internal_proto_depIdxs = nil
}
